export const lengthRates = {
    kilometer: {
        meter: val => val * 1000,
        centimeter: val => val * 100000,
        millimeter: val => val * 1e+6,
        mile: val => val / 1.609,
        yard: val => val * 1094,
        foot: val => val * 3281,
        inch: val => val * 39370,
    },
    meter: {
        kilometer: val => val / 1000,
        centimeter: val => val * 100,
        millimeter: val => val * 1000,
        mile: val => val / 1609,
        yard: val => val * 1.094,
        foot: val => val * 3.281,
        inch: val => val * 39.37,
    },
    centimeter: {
        kilometer: val => val / 100000,
        meter: val => val / 100,
        millimeter: val => val * 10,
        mile: val => val / 160900,
        yard: val => val / 91.44,
        foot: val => val / 30.48,
        inch: val => val / 2.54,
    },
    millimeter: {
        kilometer: val => val / 1e+6,
        meter: val => val / 1000,
        centimeter: val => val / 10,
        mile: val => val / 1.609e+6,
        yard: val => val / 914.4,
        foot: val => val / 304.8,
        inch: val => val / 25.4,
    },
    mile: {
        kilometer: val => val * 1.609,
        meter: val => val * 1609,
        centimeter: val => val * 160900,
        millimeter: val => val * 1.609e+6,
        yard: val => val * 1760,
        foot: val => val * 5280,
        inch: val => val * 63360,
    },
    yard: {
        kilometer: val => val / 1094,
        meter: val => val / 1.094,
        centimeter: val => val * 91.44,
        millimeter: val => val * 914.4,
        mile: val => val / 1760,
        foot: val => val * 3,
        inch: val => val * 36,
    },
    foot: {
        kilometer: val => val / 3281,
        meter: val => val / 3.281,
        centimeter: val => val * 30.48,
        millimeter: val => val * 304.8,
        mile: val => val / 5280,
        yard: val => val / 3,
        inch: val => val * 12,
    },
    inch: {
        kilometer: val => val / 39370,
        meter: val => val / 39.37,
        centimeter: val => val * 2.54,
        millimeter: val => val * 25.4,
        mile: val => val / 63360,
        yard: val => val / 36,
        foot: val => val / 12,
    },
}